name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Lowercase Repository Name
        run: |
          echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Deploy to K3s
        run: |
          kubectl apply -f k8s/ -n maya-geo
          kubectl set image deployment/geo-course \
            geo-course=ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -n maya-geo

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/geo-course -n maya-geo --timeout=180s